# Generated by Django 5.2.1 on 2025-08-20 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject (e.g., Mathematics, Physics)', max_length=100)),
                ('delflag', models.BooleanField(default=False)),
                ('requires_payment', models.BooleanField(default=False, help_text='If true, user must pay to access tests under this subject')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter price for accessing the test. Used only if requires_payment=True', max_digits=7)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from subject name', null=True, unique=True)),
                ('category', models.ForeignKey(help_text='Category associated with this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
